# Generated by Django 5.0.3 on 2024-04-03 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_review_title_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='animal',
            field=models.ManyToManyField(to='main.animal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sale'),
        ),
        migrations.AlterField(
            model_name='productcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
